# Generated by Django 5.2.4 on 2025-07-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_enquiryadmin_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='user',
        ),
    ]
